[package]
name = "wheel-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
uwheel = { version = "0.2.0", default-features = false, features = [
    "sync",
    "min_max",
    "sum",
] }
datafusion = "38.0.0"
async-trait = "0.1.81"
chrono = "0.4.38"
bitpacking = "0.9.2"
tokio = "1.38.1"
futures = "0.3.30"


[dev-dependencies]
clap = { version = "3.2", features = ["derive"] }
