[package]
name = "datafusion-uwheel"
version.workspace = true
edition.workspace = true

[dependencies]
datafusion.workspace = true
uwheel.workspace = true
async-trait.workspace = true
chrono.workspace = true
bitpacking.workspace = true
futures.workspace = true


[dev-dependencies]
tokio = "1.38.1"
