[package]
name = "datafusion-uwheel"
version.workspace = true
edition.workspace = true

[dependencies]
datafusion.workspace = true
uwheel.workspace = true
chrono.workspace = true
bitpacking.workspace = true

[dev-dependencies]
tokio = "1.38.1"
